[package]
name = "iot"
version = "0.1.0"
edition = "2021"

[dependencies]
pin = "0.2.8"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
pin-project = "1.1.4"
#bytes = "1.7.2"
num-traits = "0.2.19"
tokio-stream = "0.1.16"
env_logger = "0.11.5"
log = "0.4.22"
